### ISSUE TITLE
pulumi up fails

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [atomist-blogs/iac-gke#3]
Hi David.
I tried to install with pulumi. But if fails with the exception below.
Do you have an idea what went wrong. (The pulumi demo example works)
Best regards
Stefan

```
pulumi config set gcp:project test-k8s-cluster                
pulumi config set --secret billingAccount xxxxxxxxxxxxxxxxx
pulumi config set dnsName test.miles-ahead.cloud              
pulumi up 
Previewing update (iac-gke)

View Live: https://app.pulumi.com/Miles-Ahead-Digital/iac-gke/iac-gke/previews/24b3ddaf-311c-4706-89d7-82980b700b7d

     Type                 Name             Plan       Info
 +   pulumi:pulumi:Stack  iac-gke-iac-gke  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (iac-gke-iac-gke):
    error: Running program '/Users/sklose/Downloads/iac-gke-main' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(48,26): error TS2694: Namespace '"/Users/sklose/Downloads/iac-gke-main/node_modules/@pulumi/gcp/index"' has no exported member 'serviceAccount'.
    index.ts(53,54): error TS2694: Namespace '"/Users/sklose/Downloads/iac-gke-main/node_modules/@pulumi/gcp/index"' has no exported member 'serviceAccount'.
    index.ts(126,37): error TS2339: Property 'serviceAccount' does not exist on type 'typeof import("/Users/sklose/Downloads/iac-gke-main/node_modules/@pulumi/gcp/index")'.
    index.ts(418,7): error TS2694: Namespace '"/Users/sklose/Downloads/iac-gke-main/node_modules/@pulumi/gcp/index"' has no exported member 'serviceAccount'.
    
        at createTSError (/Users/sklose/Downloads/iac-gke-main/node_modules/ts-node/src/index.ts:261:12)
        at getOutput (/Users/sklose/Downloads/iac-gke-main/node_modules/ts-node/src/index.ts:367:40)
        at Object.compile (/Users/sklose/Downloads/iac-gke-main/node_modules/ts-node/src/index.ts:558:11)
        at Module.m._compile (/Users/sklose/Downloads/iac-gke-main/node_modules/ts-node/src/index.ts:439:43)
        at Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/sklose/Downloads/iac-gke-main/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:1100:32)
        at Function.Module._load (internal/modules/cjs/loader.js:962:14)
        at Module.require (internal/modules/cjs/loader.js:1140:19)
        at require (internal/modules/cjs/helpers.js:75:18)
 
```
 

![CleanShot 2021-03-11 at 18 22 22@2x](https://user-images.githubusercontent.com/58099738/110828136-0924a080-8297-11eb-8b86-d508b315b54a.png)

**Comment by Miles-Ahead-Digital** [comment]
fix not need anymore - I did the setup with gcloud und kubectl
